from pathlib import Path
import base64
import streamlit as st
import streamlit.components.v1 as components

# Asset paths
HERO_IMG_PATH = Path(__file__).parent.parent / "ui" / "static" / "Sat.jpg"
SOLAR_IMG_PATH = Path(__file__).parent.parent / "ui" / "static" / "solar.jpg"


def _img_data_uri_file(path: Path) -> str:
    """Return a data: URI for a local image (png/jpg/svg)."""
    try:
        if not path.is_file():
            return ""
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        mime = "image/jpeg" if path.suffix.lower() in (".jpg", ".jpeg") else "image/png"
        return f"data:{mime};base64,{b64}"
    except Exception as e:
        st.write(f"Error in base64 encoding: {e}")
        return ""


def render():
    # Wrapper so our global CSS can add safe bottom padding on phones
    st.markdown("<div class='page-pad'>", unsafe_allow_html=True)

    # ========== TINY HOME ASSISTANT (ABOVE HERO) ==========
    # Slim "Quick start" helper, not a second navbar
    st.markdown(
        """
<div class="home-mini-assistant">
  <div class="home-mini-assistant-inner">
    <div class="home-mini-assistant-left">
      <div class="home-mini-avatar">🛰️</div>
      <div>
        <div class="home-mini-title">Quick start</div>
        <div class="home-mini-sub">
          Pick one of the main tasks to jump into SIS.
        </div>
      </div>
    </div>
    <div class="home-mini-actions">
      <a class="home-mini-pill" href="?page=Radiation">☀️ Explore radiation maps</a>
      <a class="home-mini-pill" href="?page=Basics">📚 Learn the basics</a>
      <a class="home-mini-pill" href="?page=Assistant">🤖 Ask the chatbot</a>
      <a class="home-mini-pill" href="?page=Grid%20Analysis">Open grid analysis map</a>
    </div>
  </div>
</div>
        """,
        unsafe_allow_html=True,
    )

    # ===== Hero (top) =====
    hero_uri = _img_data_uri_file(HERO_IMG_PATH)
    st.markdown(
        f"""
<div class="hero" style="background-image:url('{hero_uri}'); background-size:cover; background-position:center; background-repeat:no-repeat; background-blend-mode:overlay;">
  <div class="content">
    <h1>SIS — Satellite Imagery for Solar Radiation Estimation &amp; Grid Congestion Analysis</h1>
    <h4>Sustainable Data &amp; AI Applications Research Group - Fontys Innovation Lab</h4>
    <p>
      Solar energy is growing fast in the Netherlands. That’s great for sustainability but when solar production
      exceeds local demand or transport capacity, grid congestion can follow. To plan and operate the grid smoothly,
      we need reliable signals about where and when radiation is high and we need them to be transparent and reproducible.
    </p>
  </div>
</div>
""",
        unsafe_allow_html=True,
    )

    # ===== Explanatory split section (middle) =====
    solar_uri = _img_data_uri_file(SOLAR_IMG_PATH)
    st.markdown(
        f"""
<div class="hero-split">
  <div class="content">
    <h1>Satellite Imagery, Solar Radiation and Grid Congestion</h1>
    <p>
      Satellite images are photographs of Earth taken from space. These images help us see the surface of the Earth and track
      changes in weather and sunlight. For solar energy, they show how much sunlight an area is receiving, which is essential
      for predicting solar power generation.
    </p>
    <p>
      Solar radiation is the energy that comes from the Sun. This energy is used to generate solar power. It includes direct sunlight
      and diffuse sunlight, which we capture using solar panels. Knowing how much radiation is available helps us plan solar energy
      production efficiently.
    </p>
    <p>
      Grid congestion happens when the electricity generated by solar panels is too much for the power grid to handle. This can lead
      to inefficiencies or even curtailment if the power cannot be properly transmitted to where it’s needed. By predicting when and
      where this might happen, we can avoid these problems.
    </p>
  </div>
  <div class="hero-img">
    <img src="{solar_uri}" alt="Solar Panels" style="width:100%;height:auto;border-radius:12px;border:1px solid rgba(255,255,255,.1);box-shadow:0 12px 28px rgba(0,0,0,.35);" />
  </div>
</div>
""",
        unsafe_allow_html=True,
    )

    # ===== Data Used in SIS (bottom) =====
    st.markdown(
        "<h2 style='font-family: Tahoma, sans-serif; margin-top:26px;'>Data Used in SIS</h2>",
        unsafe_allow_html=True,
    )

    cards_html = """
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>
  :root { --card-gap: 20px; }
  body { margin:0; font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; }
  .cards {
    display:flex; flex-wrap:wrap; gap: var(--card-gap);
    justify-content:center; align-items:stretch;
    max-width:1100px; margin:16px auto 24px; padding: 0 12px;
  }
  .card {
    background:#ffffff; border-radius:14px; padding:24px;
    box-shadow:0 6px 14px rgba(0,0,0,0.15);
    flex: 1 1 300px; min-width: 260px; max-width: 360px;
    text-align:center; transition:transform .2s ease;
  }
  .card:hover { transform: translateY(-2px); }
  .card h3 { margin:0 0 10px; font-size:22px; font-weight:800; }
  .card p  { margin:0 0 12px; font-size:16px; line-height:1.5; color:#333; }
  .card a  { color:#0a63ff; text-decoration:none; font-weight:800; }

  @media (max-width: 600px) {
    .cards { gap: 14px; }
    .card { flex: 1 1 100%; min-width: 0; padding:18px; }
    .card h3 { font-size:20px; }
    .card p  { font-size:15px; line-height:1.45; }
  }
</style>
</head>
<body>
  <div class="cards">
    <div class="card">
      <h3 style="color:#4CAF50;">Sentinel-2</h3>
      <p>European optical imagery for land and vegetation. Helps us study surface patterns that relate to irradiance across regions.</p>
      <a href="https://dataspace.copernicus.eu/data-collections/copernicus-sentinel-data/sentinel-2" target="_blank">Learn more</a>
    </div>

    <div class="card">
      <h3 style="color:#2196F3;">CAMS</h3>
      <p>Copernicus Atmosphere Monitoring Service time series and forecasts of solar radiation and atmospheric conditions.</p>
      <a href="https://ads.atmosphere.copernicus.eu/datasets/cams-solar-radiation-timeseries?tab=overview" target="_blank">Learn more</a>
    </div>

    <div class="card">
      <h3 style="color:#FF9800;">SARAH-3</h3>
      <p>Satellite-derived hourly to sub-hourly surface irradiance from CM SAF – high-quality coverage for Europe and beyond.</p>
      <a href="https://www.cmsaf.eu/EN/Home/home_node.html" target="_blank">Learn more</a>
    </div>

    <div class="card">
      <h3 style="color:#795548;">Digital Elevation Model (DEM)</h3>
      <p>
        High-resolution terrain heights for the Netherlands. Used to derive slope and aspect and to explore how small
        height differences might influence sunlight patterns and potential grid congestion risk.
      </p>
      <a href="https://portal.opentopography.org/raster?opentopoID=OTSDEM.092022.3035.1" target="_blank">Learn more</a>
    </div>
  </div>
</body>
</html>
    """
    components.html(cards_html, height=900, scrolling=False)

    st.markdown("<div class='mobile-bottom-spacer'></div>", unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)  # close .page-pad
